
name: Release & deploy & create next iteration version

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release_version:
        description: "Release number version to create"
        requdsired: true
      next_version:
        description: "SNAPSHOT number of the next development version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Check compilation
        run: ./gradlew clean install -x :features:cycle

  prepare-release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.TOKEN_RELEASE}}
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Configure Git user email
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Set release version
        run: |
          echo ${{ github.event.inputs.release_version }}  > ${GITHUB_WORKSPACE}/domain/version.txt
          echo ${{ github.event.inputs.release_version }} > ${GITHUB_WORKSPACE}/domain-testing/version.txt
          echo ${{ github.event.inputs.release_version }} > ${GITHUB_WORKSPACE}/features/version.txt
          echo ${{ github.event.inputs.release_version }} > ${GITHUB_WORKSPACE}/migrations/version.txt
          git add . && git commit -m "[github action]: prepare release $RELEASE"
        env:
          RELEASE: ${{ github.event.inputs.release_version }}